### ISSUE TITLE
[Windows] Stuck Loading

### ISSUE THREAD

**Issue by 3vanD** [ItsSim/fsolauncher#10]
I successfully downloaded the launcher and everything but when I went to download _The Sims Online (FilePlanet)_ it stopped loading at 27%. I already tried deleting the whole launcher and everything but it still kept its progress.

**Comment by ItsSim** [comment]
Hello!

This seems to be a network issue. To confirm, you noticed that your The Sims Online (FilePlanet) download stopped at 27% and never progressed at that point, correct?

Have you tried running the installer again (only the _The Sims Online_ part, not complete installation) by clicking on it in the installer tab? If so, does it always stop at 27%? 

(If on Windows) Do you have any antivirus software that may be firewalling these downloads? If so, try adding FreeSO Launcher as an exception, or disable it while doing the installation.

If the issue keeps happening, a last resort would be to download the files manually through a browser: https://archive.org/download/TheSimsOnline_201802/TSO.zip, extract it to a folder and run Setup.exe. Once it finishes, close this setup and start the launcher. Continue by installing FreeSO, and finally, launch the game.

**Comment by ItsSim** [comment]
Closed after 24h of inactivity.
