### ISSUE TITLE
[Windows, Mac] Change launcher language option

### ISSUE THREAD

**Issue by macmmm81** [ItsSim/fsolauncher#13]
Please add an option to change launcher language, as it is not currently possible.

**Comment by ItsSim** [comment]
The approach would be to add a new selector element in the Settings page, and saving this value in FSOLauncher.ini, just like the other settings available.

The first option of this setting should be "System default", which would be the language of the user’s OS. Then it should include an option for each language available in the launcher: English, Spanish, Italian, Russian, Polish, Dutch. 

These strings should be in the native language. For example: "Spanish" should show up as "Español", no matter what the current launcher settings are. The only translated string would be the first one: "System default".

**Comment by ItsSim** [comment]
Launcher language option dropdown added in the Settings page. Will be available in **1.8.4**.

![fsolauncher_0Gs85UlSmi](https://user-images.githubusercontent.com/35347872/137819261-97826380-c6e8-4749-ab59-b56b603b9791.png)
![fsolauncher_LT2h2t7MgW](https://user-images.githubusercontent.com/35347872/137819304-ba19b91c-fb23-469f-92e4-e57fb704b049.png)
