### ISSUE TITLE
[Windows, Mac] Improve developer documentation

### ISSUE THREAD

**Issue by ItsSim** [ItsSim/fsolauncher#26]
The Developer Documentation (https://github.com/ItsSim/fsolauncher/wiki/Development-guide) should be expanded to include the following topics:

- Contribution rules (Basic rules for pull-requests).
- Code style (dictated by ESLint rules, but just a more formal description).
- Using IPC (via library/ipc-bridge.js) to communicate between the renderer and main processes.
- Using modals (via library/modal.js).
- Creating new launcher tabs.
- Adding new components to the Installer tab.
- Debugging (main and renderer).

**Comment by tomgrice** [comment]
This would actually be very useful haha. I've actually learnt quite a bit about node and electron from trying to fix one thing. I haven't actually used electron or node before and haven't used JS in some time, so the extra guidance on code style etc would be helpful.

**Comment by ItsSim** [comment]
Added two pages to the [developer documentation](https://github.com/ItsSim/fsolauncher/wiki/Development-guide):
* [Code Style](https://github.com/ItsSim/fsolauncher/wiki/Code-Style)
* [Using IPC](https://github.com/ItsSim/fsolauncher/wiki/Using-IPC-(Inter-Process-Communication))

**Comment by ItsSim** [comment]
Added two more pages:
* [Using Modals](https://github.com/ItsSim/fsolauncher/wiki/Using-Modals)
* [Creating Sidebar Tabs and Pages](https://github.com/ItsSim/fsolauncher/wiki/Creating-Sidebar-Tabs-and-Pages)

**Comment by ItsSim** [comment]
Added all planned documentation to the [developer documentation](https://github.com/ItsSim/fsolauncher/wiki/Development-guide).

* [Creating Installers](https://github.com/ItsSim/fsolauncher/wiki/Creating-Installers)
* [How to Contribute (CONTRIBUTING.md)](https://github.com/ItsSim/fsolauncher/blob/master/CONTRIBUTING.md)
* [Debugging](https://github.com/ItsSim/fsolauncher/wiki/Debugging)
