### ISSUE TITLE
[Windows, Mac] Simitone menu item not aligned

### ISSUE THREAD

**Issue by ItsSim** [ItsSim/fsolauncher#29]
**Describe the bug**
The Simitone menu item (icon and text) is not aligned with the rest of menu items.

Also using this issue to try out the new issue template.

**To Reproduce**
1. Open the launcher.
2. See the bottom of the sidebar menu, where the Simitone menu item is.

**Expected behavior**
The Simitone icon and text should be aligned with the rest of menu items.

**Screenshots**
![image](https://user-images.githubusercontent.com/35347872/152662521-34b09e29-1e24-4640-bc61-18e9b3ca7225.png)
![image](https://user-images.githubusercontent.com/35347872/152662656-ff59d497-09e7-4122-bd63-81802cb462ea.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11
 
**Additional context**
The Simitone menu item is the only item that uses an SVG element to render the icon, which is most likely why the alignment isn’t correct. Probably need to modify CSS to accommodate it.

**Comment by tomgrice** [comment]
All sorted I think. Tried to make it somewhat generic in case another SVG icon is added in the future, but either the CSS or the SVG code (to standardize the icon size) will probably need tweaking slightly if this happens.

#31

**Comment by ItsSim** [comment]
Closed with #31, thanks.

I think making sure any future SVG elements are the same size will be sufficient.
