### ISSUE TITLE
[Windows/Mac] Home refresh button

### ISSUE THREAD

**Issue by ItsSim** [ItsSim/fsolauncher#37]
**Is your feature request related to a problem? Please describe.**
There is currently no way to refresh the home page content (RSS, Twitter).

**Describe the solution you'd like**
Allow the user to refresh the home page content with a "Refresh" button in the header.

**Describe alternatives you've considered**
There is no other way to do this right now.

**Additional context**
Should be implemented as a button in the header that, when clicked, refreshes the RSS feed and Twitter feed.
There are functions in the src/fsolauncher_ui/client.js file that already do this, these functions should be called upon user request.
This feature is client-side only, meaning that only the fsolauncher.pug/client.js files should be modified.

Example of how the button could be made (I don't have a high-res homepage screenshot right now, but this button would be **ON THE HOMEPAGE**, not Settings): Icon is material-icons, already included in the pug file.

![launcher-refresh](https://user-images.githubusercontent.com/35347872/158263322-c0b39320-8d1b-41e5-9994-da155ad6a6ef.png)
A tooltip should be displayed "Refreshing content..." or something similar, while processing.

**Comment by ItsSim** [comment]
+Spamming the button should be prevented, 1 req/s limit maybe.

**Comment by tomgrice** [comment]
Just submitted a pull request for this one.

**Comment by ItsSim** [comment]
Thanks for the PR @tomgrice! Merged it and works great.

Reopening though because I feel like there's too many default buttons already. Playing around with some other options, trying to decide on one.

![image](https://user-images.githubusercontent.com/35347872/163221380-7402101e-5441-4ac7-a5a7-b2bfe51672fa.png)

**Comment by tomgrice** [comment]
I did consider this as the default looks a bit clunky for something as simple as refresh.
Options could be to use material icons without a button (just an icon), or use an SVG image like the Simitone icon.

Other option would be to poll for updates every minute (hopefully be able to get that from page metadata) or so and do a full refresh if the page has been updated.

Or could have individual smaller icons next to each section?

![refresh](https://user-images.githubusercontent.com/14261788/163302111-c49da870-8ba4-4e31-854b-eb59da92cd01.png)

Just a mockup, I would probably have the refresh icons slightly smaller, and slightly faded and become more visible on hover.

**Comment by ItsSim** [comment]
The two smaller buttons option does seem nicest, but I'm not sure if a user would want to individually update both sections. I think of it more as a "give me any FreeSO news" feature.
Also, I've been wanting to put something on the right side of that header for the longest time because it seemed too empty.
The polling option is not possible, I've agreed to the launcher hitting the website the least it can.
So, a nice icon in the header instead of a button would be the best option. Probably a smaller icon than the one I posted.

**Comment by tomgrice** [comment]
Cool - i've given it a shot. Should be easy to change icon to whatever style is needed.

**Comment by tomgrice** [comment]
Just noticed it gives some weird results when theme is changed. I will fix shortly.

**Comment by ItsSim** [comment]
> Just noticed it gives some weird results when theme is changed. I will fix shortly.

I merged and fixed the appearance for all themes. Closing!

**Comment by ItsSim** [comment]
<img width="1202" alt="Screenshot 2022-04-26 at 14 41 28" src="https://user-images.githubusercontent.com/35347872/165302102-246e0295-5e72-40e4-bbc6-33d35e150bfe.png">

**Comment by tomgrice** [comment]
Looks awesome :)
