### ISSUE TITLE
[Windows] TSOVersionPatcher.exe throws an exception during Full Installation.

### ISSUE THREAD

**Issue by tomgrice** [ItsSim/fsolauncher#44]
**Describe the bug**
During installation, the dialog below pops up for me. I noticed this exception when updating the Lutris (Linux) installer for FSO.
I took the patch step out of the install as it no longer seemed to be necessary. Has the TSO(.docx/.zip) file that is fetched been replaced with an already patched version? 

Just posting here to double check but I think moving forward this step can be simply removed from the installation process?

**Launcher Version**
1.8.12

**To Reproduce**
From a 'clean slate' (no TSO/FSO installed)
1. Download and install FSOLauncher.
2. Start a 'Complete Installation'
3. The dialog screenshotted below pops up after TSO's .cab files have all been extracted.
4. Once 'OK' is clicked the installation process continues without consequence.

**Screenshots**
![image](https://user-images.githubusercontent.com/14261788/174278666-7ffd2296-c768-4e66-8723-d04fbef819aa.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10
 - Build: 19042

**Comment by ItsSim** [comment]
Yes, this can be removed. It was needed at first but then the patching was added to the client (FreeSO.exe) itself. So it's not needed in the launcher anymore.

**Comment by ItsSim** [comment]
Fixed with #45, thanks.
